name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: get nix
        uses: DeterminateSystems/determinate-nix-action@main
      - name: build the flake
        run: |
          nix build .
